root: true
extends:
  - actano-base
  - plugin:eslint-comments/recommended
  - plugin:flowtype/recommended

parser: babel-eslint

plugins:
  - flowtype

rules:
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - 'test/**/*.js'
  import/prefer-default-export:
    - off

overrides:
  - files:
      - 'test/**/*.js'
    env:
      mocha: true
